### ISSUE TITLE
Criar modelagem e popular tabelas no banco de dados

### ISSUE THREAD

**Issue by natanascimento** [nataliafonseca/abfln#6]
- [x] Definir modelagem dos dados baseado no foi solicitado pelo cliente;
- [x] Criar queries em SQL baseado no modelo de entidade-relacionamento;
- [x] Criar pasta "/database" no mesmo nível do "/frontend" e "/backend":
     - [x] Criar pasta "/database/model" para armazenar a modelagem dos dados;
     - [x] Criar pasta "/database/scripts" para armazenar as queries em SQL;

**Comment by BrunoCesar10** [comment]
Tabelas e entidades criadas e funcionais
